from sqlalchemy import Column, Integer, Float, String, DateTime, ForeignKey, JSON
from sqlalchemy.orm import relationship
from datetime import datetime, timezone
from core.database import Base

class Event(Base):
    __tablename__="events"

    id = Column(Integer, primary_key=True, index=True)
    session_id = Column(Integer, ForeignKey("sessions.id"), nullable=False)
    
    timestamp = Column(DateTime, default=lambda: datetime.now(timezone.utc))
    category = Column(String, nullable=False) # 'EYE/HEAD', 'YOLO', 'ANOMALY'
    description = Column(String, nullable=False)  # 'Student looked away', 'Cell Phone detected'
    details = Column(String, nullable=False) #  'direction=CENTER yaw=-19.7°'

    # Stores the path to the snapshot image generated by the AI ("AI_Engine/evidence/pic_01.jpg").
    evidence_url = Column(String, nullable=True)

    # Relationship: the 
    # logged under (N:1): Multiple Proctoring Events are tied to one sessions record.
    session = relationship("Session", back_populates="events")  # WE MATCH THE VARIABLE NAME (the events variable in session ) AND NOT THE TABLE NOR THE CLASS NAME.

